### ISSUE TITLE
 Inquiry Regarding the Validity of the URL in Case2

### ISSUE THREAD

**Issue by cynical-z** [gladcolor/LLM-Geo#6]
I hope this message finds you well. I am currently exploring the functionalities provided in Case2 of your project and noticed that the URL provided seems to be inaccessible. I wanted to reach out and inquire whether the URL is still valid or if there have been any changes.

If there is an updated URL or if you could provide guidance on accessing the relevant data, I would greatly appreciate it. Your assistance in this matter would be invaluable for my ongoing work with your project.

Thank you for your time and consideration.

Best regards,
pmd

**Comment by gladcolor** [comment]
Hello @cynical-z! We are very sorry that the API has been shut down due to the move of the research team.  Currently, we are still working on the purchase of machines and then will set up the environment. What kind of projects are you working on? We may be able to provide you with the necessary data.
